
package com.mycompany.proyecto;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class Pagina_Inicio extends javax.swing.JPanel {

    public static void main(String[] args) {
    // Ruta de la imagen original
    String originalImagePath = "src/main/java/com/mycompany/proyecto/Imagenes/Logo.png";
    
    // Tamaño deseado de la imagen redimensionada
    int newWidth = 200;
    int newHeight = 200;
    
    try {
            // Lee la imagen original desde el archivo
            File originalFile = new File(originalImagePath);
            BufferedImage originalImage = ImageIO.read(originalFile);
            
            // Redimensiona la imagen
            Image resizedImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_DEFAULT);
            
            // Crea un ImageIcon con la imagen redimensionada
            ImageIcon icon = new ImageIcon(resizedImage);
            
            // Crea un JLabel para mostrar la imagen
            JLabel label = new JLabel(icon);
            
            // Crea y configura un JFrame para contener el JLabel
            JFrame frame = new JFrame("Imagen Redimensionada");
            frame.add(label);
            frame.pack();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setVisible(true);
        } catch (IOException ex) {
            System.out.println("Error al procesar la imagen: " + ex.getMessage());
        }
    
    
    public Pagina_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
